const perfils =[
    {
        id : 1,
        foto : "/gato.jpg",
        cargo: "Membro",
        nome : "Chico",
        email : "chico@alunos.utfpr.edu.br",
        telefone : "43 99999-0000",
        setor : "Material",
        curiosidade : "Top 50 no raking de Free Fire nacional",
        curso : "ADS",
        periodo : "Terceiro",
        ingles : "Intermediário",
        cidade: "Leópolis",
        aniversario : "29/02",
        hobbie : ["Sinuca","Free Fire","Jogo do Bicho"],
    },
    {
        id : 3,
        foto : "/2.png",
        cargo: "Membro",
        nome : "Marina",
        email : "marina@alunos.utfpr.edu.br",
        telefone : "43 98888-1111",
        setor : "Biblioteca",
        curiosidade : "Tem uma coleção com mais de 200 livros de fantasia",
        curso : "Design Gráfico",
        periodo : "Segundo",
        ingles : "Avançado",
        cidade: "Cornélio Procópio",
        aniversario : "15/04",
        hobbie : ["Leitura","Desenhar","Café"],
    },
    {
        id : 4,
        foto : "/3.png",
        cargo: "representante",
        nome : "Lucas",
        email : "lucas@alunos.utfpr.edu.br",
        telefone : "43 97777-2222",
        setor : "Tecnologia",
        curiosidade : "Construiu seu próprio PC com peças recicladas",
        curso : "Engenharia de Software",
        periodo : "Quarto",
        ingles : "Intermediário",
        cidade: "Assaí",
        aniversario : "03/09",
        hobbie : ["Programar","Futebol","Séries"],
    },
    {
        id : 5,
        foto : "/4.png",
        cargo: "membro",
        nome : "Bruna",
        email : "bruna@alunos.utfpr.edu.br",
        telefone : "43 96666-3333",
        setor : "Financeiro",
        curiosidade : "Já fez intercâmbio na Nova Zelândia",
        curso : "Administração",
        periodo : "Quinto",
        ingles : "Avançado",
        cidade: "Bandeirantes",
        aniversario : "11/12",
        hobbie : ["Viajar","Fotografia","Ciclismo"],
    },
    {
        id : 6,
        foto : "/5.png",
        cargo: "coordenação",
        nome : "Rafael",
        email : "rafael@alunos.utfpr.edu.br",
        telefone : "43 95555-4444",
        setor : "Compras",
        curiosidade : "É faixa preta em karatê",
        curso : "Educação Física",
        periodo : "Sétimo",
        ingles : "Básico",
        cidade: "Andirá",
        aniversario : "24/06",
        hobbie : ["Academia","Jogos","Animes"],
    },
    {
        id : 7,
        foto : "/6.png",
        nome : "Letícia",
        cargo: "membro",
        email : "leticia@alunos.utfpr.edu.br",
        telefone : "43 94444-5555",
        setor : "Comunicação",
        curiosidade : "Tem um canal no YouTube sobre cultura japonesa",
        curso : "Publicidade e Propaganda",
        periodo : "Sexto",
        ingles : "Avançado",
        cidade: "Uraí",
        aniversario : "08/01",
        hobbie : ["Edição de vídeo","Culinária japonesa","Mangás"],
    },
    {
        id : 8,
        foto : "/7.png",
        cargo: "membro",
        nome : "Gustavo",
        email : "gustavo@alunos.utfpr.edu.br",
        telefone : "43 93333-6666",
        setor : "TI",
        curiosidade : "Conseguiu um estágio no exterior aos 19 anos",
        curso : "Engenharia da Computação",
        periodo : "Terceiro",
        ingles : "Fluente",
        cidade: "Sertaneja",
        aniversario : "19/05",
        hobbie : ["Tecnologia","Viagens","Cinema"],
    },
    {
        id : 9,
        foto : "/8.png",
        cargo: "representante",
        nome : "Fernanda",
        email : "fernanda@alunos.utfpr.edu.br",
        telefone : "43 92222-7777",
        setor : "RH",
        curiosidade : "Toca violino desde os 8 anos",
        curso : "Psicologia",
        periodo : "Oitavo",
        ingles : "Intermediário",
        cidade: "Santa Mariana",
        aniversario : "27/10",
        hobbie : ["Música","Pintura","Yoga"],
    },
    {
        id : 10,
        foto : "/9.png",
        cargo: "membro",
        nome : "Eduardo",
        email : "eduardo@alunos.utfpr.edu.br",
        telefone : "43 91111-8888",
        setor : "Manutenção",
        curiosidade : "É apicultor nas horas vagas",
        curso : "Engenharia Ambiental",
        periodo : "Quinto",
        ingles : "Básico",
        cidade: "Nova Fátima",
        aniversario : "21/08",
        hobbie : ["Natureza","Ciclismo","Mecânica"],
    }
]

export const getPerfils = async () => {
    return perfils;
}